# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funstar', '0005_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=200),
        ),
    ]
